#!/usr/bin/env python3
"""Build a pitch-oriented chronic absenteeism and attendance operations report."""

from __future__ import annotations

import argparse
import csv
import json
import re
from collections import defaultdict
from datetime import date
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent.parent
INPUT_PATH = ROOT / "outputs" / "lcaps_json" / "all_lcaps.json"
OPPORTUNITY_DIR = ROOT / "outputs" / "opportunity_research"
OUTPUT_DIR = ROOT / "outputs" / "opportunity_research"

ATTENDANCE_AREA_KEY = "chronic_absenteeism"
NEGATIVE_STATUSES = {"off_track", "moving_away"}

EXPLICIT_ATTENDANCE_KEYWORDS = (
    "attendance",
    "absentee",
    "truancy",
    "re-engagement",
    "reengagement",
    "absence",
    "sart",
    "sarb",
    "a2a",
    "schoolstatus",
    "attention2attendance",
    "home visit",
)

WORKFLOW_KEYWORDS = (
    "message",
    "messaging",
    "communication",
    "outreach",
    "liaison",
    "home visit",
    "conference",
    "portal",
    "phone",
    "call",
    "text",
    "notification",
    "team",
    "committee",
)

TACTIC_PATTERNS: dict[str, tuple[str, ...]] = {
    "Attendance Platforms": ("a2a", "attention2attendance", "schoolstatus"),
    "Home Visits": ("home visit",),
    "SART / SARB": ("sart", "sarb"),
    "Attendance Teams / Protocols": ("attendance team", "attendance committee", "protocol"),
    "Messaging / Outreach": ("attendance messaging", "messaging", "personal outreach", "communication", "outreach"),
    "Liaisons / Family Support": ("liaison", "family conference", "re-engagement", "reengagement"),
}


def normalize_text(value: Any) -> str:
    text = str(value or "")
    replacements = {
        "\u2010": "-",
        "\u2011": "-",
        "\u2012": "-",
        "\u2013": "-",
        "\u2014": "-",
        "\u2212": "-",
        "\xa0": " ",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    text = text.replace("\r", "\n")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def compact_text(value: Any) -> str:
    return re.sub(r"\s+", " ", normalize_text(value)).strip()


def format_currency(value: float) -> str:
    return f"${value:,.0f}"


def format_pct(value: float) -> str:
    return f"{value * 100:.1f}%"


def write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, Any]]) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def markdown_table(headers: list[str], rows: list[list[str]]) -> str:
    output = ["| " + " | ".join(headers) + " |", "| " + " | ".join(["---"] * len(headers)) + " |"]
    output.extend("| " + " | ".join(row) + " |" for row in rows)
    return "\n".join(output)


def clean_title(title: str) -> str:
    return compact_text(title).split("(")[0].strip().lower()


def is_explicit_attendance_title(title: str) -> bool:
    cleaned = clean_title(title)
    return any(keyword in cleaned for keyword in EXPLICIT_ATTENDANCE_KEYWORDS)


def is_workflow_attendance_title(title: str) -> bool:
    cleaned = clean_title(title)
    return is_explicit_attendance_title(title) and any(keyword in cleaned for keyword in WORKFLOW_KEYWORDS)


def load_csv_rows(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input-path",
        type=Path,
        default=INPUT_PATH,
        help="Path to all_lcaps.json generated by extract_lcaps.py.",
    )
    parser.add_argument(
        "--opportunity-dir",
        type=Path,
        default=OPPORTUNITY_DIR,
        help="Directory containing opportunity_areas.csv and district_area_examples.csv.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=OUTPUT_DIR,
        help="Directory where the attendance pitch outputs should be written.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    input_path = args.input_path.resolve()
    opportunity_dir = args.opportunity_dir.resolve()
    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    payload = json.loads(input_path.read_text(encoding="utf-8"))
    districts = payload["districts"]

    opportunity_rows = load_csv_rows(opportunity_dir / "opportunity_areas.csv")
    district_area_rows = load_csv_rows(opportunity_dir / "district_area_examples.csv")

    broad_area = next(row for row in opportunity_rows if row["area_key"] == ATTENDANCE_AREA_KEY)
    broad_by_district = {
        row["district_name"]: row
        for row in district_area_rows
        if row["area_key"] == ATTENDANCE_AREA_KEY
    }

    explicit_rows: list[dict[str, Any]] = []
    tactic_hits: dict[str, list[dict[str, Any]]] = defaultdict(list)
    explicit_seen: set[tuple[str, str, str]] = set()

    district_rollup: dict[str, dict[str, Any]] = {
        district["district_name"]: {
            "district_name": district["district_name"],
            "explicit_attendance_action_count": 0,
            "explicit_attendance_action_dollars": 0.0,
            "explicit_workflow_action_count": 0,
            "explicit_workflow_action_dollars": 0.0,
            "zero_dollar_explicit_action_count": 0,
            "top_explicit_action": "",
            "top_explicit_action_dollars": 0.0,
        }
        for district in districts
    }

    for district in districts:
        district_name = district["district_name"]
        for goal in district["goals"]:
            for action in goal["actions"]:
                title = compact_text(action.get("title", ""))
                if not title:
                    continue
                key = (district_name, action.get("action_number", ""), title)
                if key in explicit_seen:
                    continue
                if not is_explicit_attendance_title(title):
                    continue

                explicit_seen.add(key)
                dollars = float(action.get("total_funds") or 0.0)
                workflow_match = is_workflow_attendance_title(title)
                description = compact_text(action.get("description", ""))
                contributing = action.get("contributing")

                row = {
                    "district_name": district_name,
                    "goal_number": goal["goal_number"],
                    "action_number": action.get("action_number", ""),
                    "title": title,
                    "description_snippet": description[:280],
                    "total_funds": dollars,
                    "contributing": contributing,
                    "explicit_workflow_title": workflow_match,
                }
                explicit_rows.append(row)

                district_summary = district_rollup[district_name]
                district_summary["explicit_attendance_action_count"] += 1
                district_summary["explicit_attendance_action_dollars"] += dollars
                if dollars == 0:
                    district_summary["zero_dollar_explicit_action_count"] += 1
                if workflow_match:
                    district_summary["explicit_workflow_action_count"] += 1
                    district_summary["explicit_workflow_action_dollars"] += dollars
                if dollars > district_summary["top_explicit_action_dollars"]:
                    district_summary["top_explicit_action_dollars"] = dollars
                    district_summary["top_explicit_action"] = title

                search_text = f"{title} {description}".lower()
                for tactic_label, patterns in TACTIC_PATTERNS.items():
                    if any(pattern in search_text for pattern in patterns):
                        tactic_hits[tactic_label].append(row)

    for district_name, summary in district_rollup.items():
        broad = broad_by_district.get(district_name, {})
        summary["broad_action_dollars"] = float(broad.get("action_dollars") or 0.0)
        summary["broad_externalizable_dollars"] = float(broad.get("externalizable_dollars") or 0.0)
        summary["broad_action_count"] = int(broad.get("action_count") or 0)
        summary["broad_metric_count"] = int(broad.get("metric_count") or 0)
        summary["movement_negative_share"] = float(broad.get("movement_negative_share") or 0.0)
        summary["pace_negative_share"] = float(broad.get("pace_negative_share") or 0.0)
        summary["metric_example_1"] = compact_text(broad.get("metric_example_1", ""))
        summary["metric_example_1_status"] = broad.get("metric_example_1_status", "")
        summary["metric_example_1_diff"] = compact_text(broad.get("metric_example_1_diff", ""))
        summary["negative_pressure"] = bool(
            summary["metric_example_1_status"] in NEGATIVE_STATUSES
            or summary["pace_negative_share"] > 0
            or summary["movement_negative_share"] >= 0.5
        )

    district_rows = sorted(
        district_rollup.values(),
        key=lambda row: (
            row["negative_pressure"],
            row["explicit_attendance_action_dollars"],
            row["broad_action_dollars"],
        ),
        reverse=True,
    )

    explicit_districts = {row["district_name"] for row in explicit_rows}
    workflow_districts = {row["district_name"] for row in explicit_rows if row["explicit_workflow_title"]}
    zero_dollar_explicit_rows = [row for row in explicit_rows if not row["total_funds"]]
    negative_explicit_districts = [
        row for row in district_rows if row["explicit_attendance_action_count"] and row["negative_pressure"]
    ]
    positive_negative_explicit_districts = [
        row for row in negative_explicit_districts if row["explicit_attendance_action_dollars"] > 0
    ]
    inflation_rows = sorted(
        district_rows,
        key=lambda row: (row["broad_action_dollars"] - row["explicit_attendance_action_dollars"]),
        reverse=True,
    )

    tactic_rows: list[dict[str, Any]] = []
    for label, rows in sorted(tactic_hits.items()):
        unique_districts = {row["district_name"] for row in rows}
        total_dollars = sum(float(row["total_funds"]) for row in rows)
        example_titles = []
        seen_examples: set[str] = set()
        for row in rows:
            title = row["title"]
            if title in seen_examples:
                continue
            example_titles.append(f"{row['district_name']}: {title}")
            seen_examples.add(title)
            if len(example_titles) == 3:
                break
        tactic_rows.append(
            {
                "tactic": label,
                "district_count": len(unique_districts),
                "action_count": len(rows),
                "matched_action_dollars": total_dollars,
                "examples": " | ".join(example_titles),
            }
        )

    explicit_csv_rows = [
        {
            **row,
            "total_funds": f"{row['total_funds']:.2f}",
            "contributing": "" if row["contributing"] is None else str(row["contributing"]),
        }
        for row in sorted(explicit_rows, key=lambda row: (row["total_funds"], row["district_name"]), reverse=True)
    ]

    district_csv_rows = [
        {
            **row,
            "explicit_attendance_action_dollars": f"{row['explicit_attendance_action_dollars']:.2f}",
            "explicit_workflow_action_dollars": f"{row['explicit_workflow_action_dollars']:.2f}",
            "broad_action_dollars": f"{row['broad_action_dollars']:.2f}",
            "broad_externalizable_dollars": f"{row['broad_externalizable_dollars']:.2f}",
            "movement_negative_share": f"{row['movement_negative_share']:.4f}",
            "pace_negative_share": f"{row['pace_negative_share']:.4f}",
        }
        for row in district_rows
    ]

    tactic_csv_rows = [
        {
            **row,
            "matched_action_dollars": f"{row['matched_action_dollars']:.2f}",
        }
        for row in tactic_rows
    ]

    write_csv(
        output_dir / "attendance_explicit_actions.csv",
        [
            "district_name",
            "goal_number",
            "action_number",
            "title",
            "description_snippet",
            "total_funds",
            "contributing",
            "explicit_workflow_title",
        ],
        explicit_csv_rows,
    )
    write_csv(
        output_dir / "attendance_district_summary.csv",
        [
            "district_name",
            "negative_pressure",
            "broad_action_dollars",
            "broad_externalizable_dollars",
            "broad_action_count",
            "broad_metric_count",
            "movement_negative_share",
            "pace_negative_share",
            "metric_example_1",
            "metric_example_1_status",
            "metric_example_1_diff",
            "explicit_attendance_action_count",
            "explicit_attendance_action_dollars",
            "explicit_workflow_action_count",
            "explicit_workflow_action_dollars",
            "zero_dollar_explicit_action_count",
            "top_explicit_action",
            "top_explicit_action_dollars",
        ],
        district_csv_rows,
    )
    write_csv(
        output_dir / "attendance_tactics.csv",
        ["tactic", "district_count", "action_count", "matched_action_dollars", "examples"],
        tactic_csv_rows,
    )

    report_lines = [
        "# Santa Clara County Attendance Pitch Report",
        "",
        f"As of {date.today().isoformat()}, this report uses the 28-district Santa Clara LCAP corpus and the county opportunity analysis to size chronic absenteeism demand, separate broad ecosystem spend from cleaner attendance line items, and surface the most sales-relevant district examples.",
        "",
        "## Headline Numbers",
        "",
        f"- Broad chronic absenteeism / attendance-recovery footprint: **{broad_area['districts_with_area']} / {len(districts)} districts**, **{broad_area['action_count']} actions**, **{broad_area['metric_count']} metrics**, and **{format_currency(float(broad_area['action_dollars']))}** in matched action dollars.",
        f"- Estimated externalizable share of that broad footprint: **{format_currency(float(broad_area['externalizable_dollars']))}**.",
        f"- Metric pressure: **{broad_area['districts_with_negative_pressure']} districts** show negative pressure, with **{format_pct(float(broad_area['movement_negative_share']))}** of movement points worsening and **{format_pct(float(broad_area['pace_negative_share']))}** of pace-scorable metrics off track or moving away.",
        f"- Conservative lower bound of explicit attendance-titled spend: **{format_currency(sum(row['explicit_attendance_action_dollars'] for row in district_rows))}** across **{len(explicit_rows)}** distinct actions in **{len(explicit_districts)}** districts.",
        f"- Even narrower workflow/communications lower bound: **{format_currency(sum(row['explicit_workflow_action_dollars'] for row in district_rows))}** across **{sum(row['explicit_workflow_action_count'] for row in district_rows)}** actions in **{len(workflow_districts)}** districts.",
        f"- Embedded but not separately priced: **{len(zero_dollar_explicit_rows)}** explicit attendance actions in **{len({row['district_name'] for row in zero_dollar_explicit_rows})}** districts carry **$0 standalone budget**, which usually means the work is embedded inside larger staffing or student-services lines.",
        "",
        "## What The Money Means",
        "",
        "There are two valid numbers in this market, and they answer different questions:",
        "",
        f"1. **Broad market sizing:** the county is already directing about **{format_currency(float(broad_area['action_dollars']))}** toward the chronic absenteeism problem set. This is the right number for showing that attendance is budget-real, county-wide, and operationally important.",
        f"2. **Clean attendance-ops budget:** the lower-bound of clearly named attendance actions is only about **{format_currency(sum(row['explicit_attendance_action_dollars'] for row in district_rows))}**. This is the right number for showing what districts are willing to call out explicitly as attendance work.",
        "",
        "The gap between those numbers is the commercial insight. A lot of attendance work is **buried inside student services, counseling, liaison, climate, wellness, and admin staffing**, which means the operational need is real even when there is not a neat attendance software line item.",
        "",
        "## Where The Broad Number Is Inflated",
        "",
        "The biggest broad attendance totals are not clean attendance budgets by themselves. They often reflect large blended support systems where chronic absenteeism is one of several problems being addressed.",
        "",
        markdown_table(
            ["District", "Broad Attendance $", "Explicit Attendance $", "Signal"],
            [
                [
                    row["district_name"],
                    format_currency(row["broad_action_dollars"]),
                    format_currency(row["explicit_attendance_action_dollars"]),
                    row["metric_example_1_status"] or "movement only",
                ]
                for row in inflation_rows[:8]
            ],
        ),
        "",
        "Examples:",
        "",
        "- **Milpitas Unified** shows **$42.6M** in the broad attendance bucket and is **off track**, but the matched dollars are dominated by broad support and administrative staffing rather than clean attendance line items.",
        "- **sunnyvale** shows **$24.5M** broad and a `moving_away` attendance signal, but the dollars are mostly embedded in broader inclusive-environment staffing and resources.",
        "- **San José Unified** shows **$31.7M** broad and an `off_track` chronic absenteeism metric, but the most explicit attendance-titled line the parser found is a much smaller **$242k** school-specific action.",
        "- **Morgan Hill Unified** shows **$13.1M** broad, yet the clean attendance-specific title layer is closer to **$235k**. The rest is embedded across student engagement, liaisons, counseling, and climate work.",
        "",
        "## Strongest Explicit Targets",
        "",
        markdown_table(
            ["District", "Explicit Attendance $", "Broad Attendance $", "Metric Signal", "Top Explicit Action"],
            [
                [
                    row["district_name"],
                    format_currency(row["explicit_attendance_action_dollars"]),
                    format_currency(row["broad_action_dollars"]),
                    row["metric_example_1_status"] or "movement only",
                    compact_text(row["top_explicit_action"])[:80],
                ]
                for row in positive_negative_explicit_districts[:10]
            ],
        ),
        "",
        "Best pitch-ready examples:",
        "",
        "- **Santa Clara Unified School District**: `Provide support and engage with students and families ... to increase regular school attendance, and decrease chronic absenteeism.` Budgeted at **$295,100** and paired with an **off_track** attendance metric.",
        "- **Evergreen Elementary**: `Attendance and re-engagement` (**$78,364**) plus `Director of Child Welfare Safety and Attendance` (**$268,773**). This is very close to an attendance-operations staffing + follow-up workflow pitch.",
        "- **Fremont Union High School District**: `Attendance` (**$376,674**) explicitly calls out strengthening **SART/SARB** processes while chronic absenteeism still shows subgroup pressure.",
        "- **Palo Alto Unified**: `Attendance & chronic absenteeism` (**$618,396**) explicitly references **family conferences and personal outreach** to understand barriers. Even though the district is not currently negative on the primary metric example, the workflow is clearly budgeted.",
        "- **Gilroy Unified**: `Attendance` (**$522,209**) is paired with a `moving_away` attendance metric, which is strong evidence of sustained pain plus budget.",
        "- **Cambrian**: `Enrollment/Engagement & Support Specialist for Improving Attendance` (**$59,087**) plus `Enhancing Student Attendance through A2A Implementation` (**$0** standalone). This is exactly the pattern where the workflow exists but the software/process budget is embedded elsewhere.",
        "- **Cupertino**: `Attendance Messaging, Protocols and Site Teams` (**$0** standalone) shows explicit process design without a separately priced line item, which is useful for a low-friction automation pitch.",
        "- **Saratoga Union**: explicit zero-dollar actions for an **Attendance Committee** and **School Refusal/Avoidance Teams**. That is a strong signal of acknowledged workflow pain even when the budget is embedded inside broader site operations.",
        "",
        "## Tactics Mentioned In The LCAPs",
        "",
        markdown_table(
            ["Tactic", "Districts", "Actions", "Matched $", "Examples"],
            [
                [
                    row["tactic"],
                    str(row["district_count"]),
                    str(row["action_count"]),
                    format_currency(row["matched_action_dollars"]),
                    row["examples"][:120],
                ]
                for row in tactic_rows
            ],
        ),
        "",
        "These tactic rows are best read as **signal counts**, not clean budget lines. They tell you what districts say they are doing operationally: platforms, home visits, attendance teams, messaging, liaisons, and re-engagement work.",
        "",
        "## Pitch Takeaways",
        "",
        "- Chronic absenteeism is county-wide: **27 of 28** districts are explicitly in the problem set, and **19** show negative metric pressure.",
        "- The broad attendance ecosystem is large enough to matter, but the clean line items are much smaller. That means you should sell against **buried labor and embedded workflow pain**, not just ask for a new software budget.",
        "- The cleanest product wedge is not generic AI calling. It is **attendance operations infrastructure**: same-day family outreach, multilingual follow-up, barrier capture, re-engagement workflows, escalation to attendance teams, and audit-ready notes back into district systems.",
        "- Districts already describe the exact manual workflows your product would touch: **family conferences, personal outreach, attendance messaging, A2A-style monitoring, SART/SARB processes, home visits, attendance teams, child welfare and attendance staffing, and community liaisons**.",
        "- The strongest near-term prospects are districts where **explicit attendance actions exist and negative pressure remains**. In this corpus that includes Santa Clara Unified, Evergreen, Gilroy, Fremont Union, Los Altos, Mt. Pleasant, and San José; Palo Alto is still attractive because the workflow is unusually explicit even without the same level of metric pressure.",
        "",
        "## Output Files",
        "",
        f"- `attendance_explicit_actions.csv`: every explicit attendance-titled action in the Santa Clara corpus.",
        f"- `attendance_district_summary.csv`: district-level summary with broad spend, explicit spend, and pressure signals.",
        f"- `attendance_tactics.csv`: tactic-level counts for platforms, home visits, messaging, liaisons, and related operations.",
    ]

    (output_dir / "chronic_absenteeism_pitch_report.md").write_text(
        "\n".join(report_lines).strip() + "\n",
        encoding="utf-8",
    )

    summary_payload = {
        "district_count": len(districts),
        "broad_attendance": broad_area,
        "explicit_attendance_action_count": len(explicit_rows),
        "explicit_attendance_district_count": len(explicit_districts),
        "explicit_attendance_action_dollars": round(
            sum(row["explicit_attendance_action_dollars"] for row in district_rows), 2
        ),
        "explicit_workflow_action_count": sum(row["explicit_workflow_action_count"] for row in district_rows),
        "explicit_workflow_district_count": len(workflow_districts),
        "explicit_workflow_action_dollars": round(
            sum(row["explicit_workflow_action_dollars"] for row in district_rows), 2
        ),
        "zero_dollar_explicit_action_count": len(zero_dollar_explicit_rows),
        "zero_dollar_explicit_district_count": len({row["district_name"] for row in zero_dollar_explicit_rows}),
        "negative_pressure_and_explicit_district_count": len(negative_explicit_districts),
    }
    (output_dir / "attendance_pitch_summary.json").write_text(
        json.dumps(summary_payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
